name = "XInts"
uuid = "44ec7380-ef09-47f3-9d1e-fb0d69e6fbdd"
authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.4"

[extras]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BitIntegers", "Test"]
